### PR TITLE
新增隐私清单文件

### PR DESCRIPTION
**Pull request by lxm1799**
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api?language=objc

### CODE REVIEW

**Comment by lxm1799** [comment]
我这边调试无法运行，仅仅新增了一个隐私文件，没有改动任何逻辑代码

**Comment by banchichen** [comment]
感谢PR，已经合并了。无法运行好像是因为IPHONEOS_DEPLOYMENT_TARGET太低导致的，我改为12了，我本地可以运行了

**Comment by banchichen** [comment]
已发布3.8.5版本

**Comment by bosszhu** [comment]
你好,我现在已经更新为3.8.5但是通过脚本检查发现这边隐私清单问题还是没有得到彻底处理,下面是分析情况,目前使用的是3.8.5版本

Analyzing TZImagePickerController ...
⚠️  Missing privacy manifest file!
API usage analysis result(s): 1
[0] NSPrivacyAccessedAPICategoryFileTimestamp:creationDate:/Users/xxxxxx/Pods/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImageManager.m
🛠️  Descriptions for the following required API reason(s) may be missing: 1
[0] NSPrivacyAccessedAPICategoryFileTimestamp

底下是MJExtension已处理的隐私清单,是正常的.
Analyzing MJExtension ...
💡 Found privacy manifest file(s): 1
[0] /Users/js_zl/Desktop/xxxxxxx/Pods/MJExtension/MJExtension/PrivacyInfo.xcprivacy
API usage analysis result(s): 0
✅ All required API reasons have been described in the privacy manifest.

**Comment by lxm1799** [comment]
因为这个隐私清单文件存放在TZ.framework 的bundle目录下，脚本可能会检测不到

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2024年04月23日 11:04 |
| 收件人 | banchichen/TZImagePickerController ***@***.***> |
| 抄送人 | lxm1799 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [banchichen/TZImagePickerController] 新增隐私清单文件 (PR #1675) |

你好,我现在已经更新为3.8.5但是通过脚本检查发现这边隐私清单问题还是没有得到彻底处理,下面是分析情况,目前使用的是3.8.5版本

Analyzing TZImagePickerController ...
⚠️ Missing privacy manifest file!
API usage analysis result(s): 1
[0] NSPrivacyAccessedAPICategoryFileTimestamp:creationDate:/Users/xxxxxx/Pods/TZImagePickerController/TZImagePickerController/TZImagePickerController/TZImageManager.m
🛠️ Descriptions for the following required API reason(s) may be missing: 1
[0] NSPrivacyAccessedAPICategoryFileTimestamp

底下是MJExtension已处理的隐私清单,是正常的.
Analyzing MJExtension ...
💡 Found privacy manifest file(s): 1
[0] /Users/js_zl/Desktop/xxxxxxx/Pods/MJExtension/MJExtension/PrivacyInfo.xcprivacy
API usage analysis result(s): 0
✅ All required API reasons have been described in the privacy manifest.

**Pull request merged**
